### ISSUE TITLE
Sacar mutex del ADC 

### ISSUE THREAD

**Issue by gustyXLE** [EmbeddedFramework/EmbeddedFramework#21]

**Comment by gmuro** [comment]
@gustyXLE la sugerencia de sacar el mutex es correcta, ya que como observamos
https://github.com/EmbeddedFramework/EmbeddedFramework/blob/master/modules/bsp_frdmkl46z/src/bsp_frdmkl46z_analog.c#L97
hace un take del mutex y
https://github.com/EmbeddedFramework/EmbeddedFramework/blob/master/modules/bsp_frdmkl46z/src/bsp_frdmkl46z_analog.c#L118
hace el give.
Esto se pensó originalmente así ya que el al comenzar una conversión no se puede iniciar otra antes de que termine la que está en curso, por lo tanto se pensó que se debía tratar al mismo con recurso y proteger su acceso con un mutex. 
El problema surge cuando el efHal_analog_startConv viene desde un callback desde la tarea timers y la lectura efHal_analog_read viene desde otra tarea (blinky_task), ya que FreeRTOS nos captura en un assert donde chequea si la tarea que tomó el mutex es la misma que la que lo devuelve. Con los recursos debería suceder eso, la tarea que lo toma debe ser la misma que lo devuelve.
La implementación bsp de los adc es bastante dependiente del micro que usemos, porque puede haber más de un adc convirtiendo en paralelo, por lo tanto hay que poner atención a las particularidades de funcionamiento del mismo.
Para el caso del KL46 donde tenemos 1 solo adc, me pareció importante conservar la protección de evitar que se realice un disparo nuevo si no terminó el anterior, por lo que decidí convertir el mutex en un semáforo binario y almacenar el valor convertido en un array según el canal correspondiente.
Al hacer eso se devuelve el semáforo en la interrupción, al finalizar la conversión.
